// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var List, colors, mime, pretty, util, utils;

  util = require('util');

  mime = require('mime');

  colors = require('colors');

  utils = require('../utils');

  pretty = utils.pretty;

  List = (function() {
    function List(_fussy, _list) {
      this._fussy = _fussy;
      this._list = _list;
      if (!utils.isArray(this._list)) {
        throw "Error: input is not an array!";
      }
    }

    List.prototype.debug = function(enabled) {
      this._debugEnabled = enabled;
      return this;
    };

    List.prototype._debug = function(x) {
      if (!(this._debugEnabled != null ? this._debugEnabled : this._fussy._debugEnabled)) {
        return;
      }
      return console.log("List".blue + "::".grey + x);
    };

    List.prototype.eachSync = function(cb) {
      var item, limit, skip, _i, _len, _ref, _ref1, _ref2;
      this._debug("eachSync");
      skip = (_ref = this._fussy._skip) != null ? _ref : 0;
      limit = (_ref1 = this._fussy._limit) != null ? _ref1 : Infinity;
      _ref2 = this._list.slice(skip, skip + limit);
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        item = _ref2[_i];
        cb(item, false);
      }
      cb(void 0, true);
    };

    List.prototype.eachAsync = function(cb) {
      var item, limit, skip, _i, _len, _ref, _ref1, _ref2;
      this._debug("eachAsync");
      skip = (_ref = this._fussy._skip) != null ? _ref : 0;
      limit = (_ref1 = this._fussy._limit) != null ? _ref1 : Infinity;
      _ref2 = this._list.slice(skip, skip + limit);
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        item = _ref2[_i];
        cb(item, false);
      }
      cb(void 0, true);
    };

    return List;

  })();

  module.exports = List;

}).call(this);
